### ISSUE TITLE
dmidecode issue

### ISSUE THREAD

**Issue by RichardLaing** [saltstack-formulas/fail2ban-formula#11]
Hi there I am getting the following error on building the container for this docker file.

[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.

I believe this is a path issue and would like to know how to solve this issue?

**Comment by gravyboat** [comment]
As that says it's just a warning usually due to which user is running Salt, or perms on a directory. It simply means that grains relying on dmidecode won't be available. What user are you running Salt as? There was some good troubleshooting done over in this issue: https://github.com/saltstack/salt/issues/2806, but this isn't an issue specifically with the fail2ban formula.
