### ISSUE TITLE
[FEATURE] Promote 'ng' states

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/fail2ban-formula#35]
### Is your feature request related to a problem?

No

### Describe the solution you'd like
Now that this formula has semantic versioning, I think it's time to start deprecating `fail2ban.ng` and then promote it to `fail2ban` which means remove all legacy code.

Steps:
* start indicating that `fail2ban.ng` is deprecated
* move `fail2ban.ng` states to `fail2ban`

### Describe alternatives you've considered
none

### Additional context

This has already been done for `nginx-formula` and others (but I don't know which).

**Comment by myii** [comment]
@daks Sounds good, these are the current deprecation steps, from previous conversions:

* https://github.com/saltstack-formulas/fail2ban-formula/issues/34#issuecomment-539986988

**Comment by myii** [comment]
@daks Stage one and two out of three provided in #36.

**Comment by myii** [comment]
We've got a significant blocker before this can be completed.  There are a number of errors when running the `ng` states, affecting all platforms:

* https://travis-ci.org/myii/fail2ban-formula/builds/635019828

**Comment by daks** [comment]
@myii Do you mean those `ng` states are broken? Hum... that's not good, and I don't know them, we are still using the legacy ones.

**Comment by Irsute** [comment]
@myii , @daks ,
maybe I'm wrong but the state fail2ban.ng.config.fail2ban fail because looking for the  salt://path-to-fail2ban-file wich is the value of pillar.exemple (loaded by the suite of kitchen.yml : https://github.com/Irsute/fail2ban-formula/blob/d41fe3f2051e2f63dbae9cfd343103f5b3228dc0/kitchen.yml#L191)
instead of fail2ban/ng/files/.
missing TOFS?

**Comment by myii** [comment]
@Irsute Good catch; while using the `pillar.example` file is intended, commenting out those lines should help so that it uses the default template.  Running it again to see how far we progress:

* https://travis-ci.org/myii/fail2ban-formula/builds/635410226

**Comment by myii** [comment]
OK, that's better.  The ones that are broken are probably due to configuration issues.  However, looking at the debug output, I've identified _another_ bug:

https://github.com/saltstack-formulas/fail2ban-formula/blob/d41fe3f2051e2f63dbae9cfd343103f5b3228dc0/fail2ban/ng/map.jinja#L23

This is supposed to be `fail2ban:ng:lookup`, so I'm running it again, mainly to make sure that `ignoreip` is used in the right file:

* https://travis-ci.org/myii/fail2ban-formula/builds/635412697

**Comment by myii** [comment]
And there you have it, fixed the configuration from the `ng:lookup` and now all platforms are passing!

**Comment by Irsute** [comment]
a big thanks @myii , 
so in good way to promote ng ^^

**Comment by myii** [comment]
@Irsute So the next few steps:

1. I'm going to test `ignoreip` in multiple jails, to make sure it is working properly.
1. I'll merge a new PR to run Kitchen for `fail2ban.ng` rather than `fail2ban`, including fixing the `lookup` bug mentioned above.
1. I'll ask you to modify your PR so that it can also be merged.

After that, the next stages of completing this issue can be looked at.

**Comment by Irsute** [comment]
PR is updated

**Comment by daks** [comment]
good job @myii
